import femaleProfile from './img/employees/female-profile.jpg'
import maleProfile from './img/employees/male-profile.jpg'

import AdamRedman from './img/employees/Adam-Redman.jpg'
import AliOrby from './img/employees/Ali-Orby.jpg'
import AmandaCruz from './img/employees/Amanda-Cruz.jpg'
import AminaRishi from './img/employees/Amina-Rishi.jpg'
import AndrewFerber from './img/employees/Andrew-Ferber.jpg'
import AnnaZiegler from './img/employees/Anna-Ziegler.jpg'
import AnnikaMatos from './img/employees/Annika-Matos.jpg'
import AprilSchwartz from './img/employees/April-Schwartz.jpg'
import AshleighDePalma from './img/employees/Ashleigh-DePalma.jpg'
import AzlundEngler from './img/employees/Azlund-Engler.jpg'
import BeckyRobertson from './img/employees/Becky-Robertson.jpg'
import BernardoArias from './img/employees/Bernardo-Arias.jpg'
import CandySchings from './img/employees/Candy-Schings.jpg'
import CarlaRosier from './img/employees/Carla-Rosier.jpg'
import CassieSehlmeyer from './img/employees/Cassie-Sehlmeyer.jpg'
import ChelseaRhoden from './img/employees/Chelsea-Rhoden.jpg'
import ChristopherGrove from './img/employees/Christopher-Grove.jpg'
import ChristaWhelan from './img/employees/Christa-Whelan.jpg'
import ChristianRomero from './img/employees/Christian-Romero.jpg'
import CristinaJohansson from './img/employees/Cristina-Johansson.jpg'
import DawnStarr from './img/employees/Dawn-Starr.jpg'
import DeliaToledo from './img/employees/Delia-Toledo.jpg'
import DianeRizzitano from './img/employees/Diane-Rizzitano.jpg'
import DominiqueGasdia from './img/employees/Dominique-Gasdia.jpg'
import DorothySmith from './img/employees/Dorothy-Smith.jpg'
import EdwardPearce from './img/employees/Edward-Pearce.jpg'
import ElizabethDosoretz from './img/employees/Elizabeth-Dosoretz.jpg'
import EllenFerguson from './img/employees/Ellen-Ferguson.jpg'
import EmilyAilinger from './img/employees/Emily-Ailinger.jpg'
import EricaKress from './img/employees/Erica-Kress.jpg'
import GinaValo from './img/employees/Gina-Valo.jpg'
import HannahThielman from './img/employees/Hannah-Thielman.jpg'
import HeatherBrien from './img/employees/Heather-Brien.jpg'
import JacquelineBannister from './img/employees/Jacqueline-Bannister.jpg'
import JairoCastillo from './img/employees/Jairo-Castillo.jpg'
import JamieMcKenzie from './img/employees/Jamie-McKenzie.jpg'
import JanPaulMojico from './img/employees/Jan-Paul-Mojico.jpg'
import JeffreyLapham from './img/employees/Jeffrey-Lapham.jpg'
import JenniferBullistron from './img/employees/Jennifer-Bullistron.jpg'
import JenniferCordeiro from './img/employees/Jennifer-Cordeiro.jpg'
import JenniferMoes from './img/employees/Jennifer-Moes.jpg'
import JenniferThompson from './img/employees/Jennifer-Thompson.jpg'
import JillMandeville from './img/employees/Jill-Mandeville.jpg'
import JoseButron from './img/employees/Jose-Butron.jpg'
import JudithTibera from './img/employees/Judith-Tibera.jpg'
import KarinSmith from './img/employees/Karin-Smith.jpg'
import KimberlyClement from './img/employees/Kimberly-Clement.jpg'
import LilianaAcosta from './img/employees/Liliana-Acosta.jpg'
import LindsayGaines from './img/employees/Lindsay-Gaines.jpg'
import LisaDiamond from './img/employees/Lisa-Diamond.jpg'
import LuisNavarrete from './img/employees/Luis-Navarrete.jpg'
import MargaretForszpaniak from './img/employees/Margaret-Forszpaniak.jpg'
import MarieBoisbel from './img/employees/Marie-Boisbel.jpg'
import MarieReeseGorski from './img/employees/Marie-Reese-Gorski.jpg'
import MatthewTargoff from './img/employees/Matthew-Targoff.jpg'
import MelanieOrben from './img/employees/Melanie-Orben.jpg'
import MichaelSchmidt from './img/employees/Michael-Schmidt.jpg'
import NathanLewis from './img/employees/Nathan-Lewis.jpg'
import NelsonMonroy from './img/employees/Nelson-Monroy.jpg'
import NicoleBolooki from './img/employees/Nicole-Bolooki.jpg'
import NicoleCochran from './img/employees/Nicole-Cochran.jpg'
import NicoleMillich from './img/employees/Nicole-Millich.jpg'
import NoelHelmic from './img/employees/Noel-Helmic.jpg'
import PatriciaSullivan from './img/employees/Patricia-Sullivan.jpg'
import PhillipCirrone from './img/employees/Phillip-Cirrone.jpg'
import RichardGonzalez from './img/employees/Richard-Gonzalez.jpg'
import SandraLanders from './img/employees/Sandra-Landers.jpg'
import ScarlettOlivaress from './img/employees/Scarlett-Olivaress.jpg'
import ScottKane from './img/employees/Scott-Kane.jpg'
import ShainaDulong from './img/employees/Shaina-Dulong.jpg'
import ShaneWalters from './img/employees/Shane-Walters.jpg'
import SharonBloom from './img/employees/Sharon-Bloom.jpg'
import SoniaGarcia from './img/employees/Sonia-Garcia.jpg'
import SonicaSharma from './img/employees/Sonica-Sharma.jpg'
import StephanieFrost from './img/employees/Stephanie-Frost.jpg'
import TiffanyScott from './img/employees/Tiffany-Scott.jpg'
import TomEdson from './img/employees/Tom-Edson.jpg'
import WayneMeddock from './img/employees/Wayne-Meddock.jpg'

export const team = [
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AdamRedman,
    location: 'Fort Myers',
    name: 'Adam Redman',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Alexandra Bithorn',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AliOrby,
    location: 'Cape Coral',
    name: 'Ali Orby',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'Western New Mexico University',
        'Florida Atlantic University',
      ],
      degrees: ['Masters in Clinical Social Work - Magna Cum Laude'],
      favoriteQuote:
        'Challenges are what make life interesting and overcoming them is what makes life meaningful',
      hobbies: ['Family', 'Exercise', 'Going to the beach'],
      hometown: 'Fort Lauderdale, FL',
      patientAgesSeen: ['12+', 'parents'],
      specialCertifications: [
        'Advanced Training in: Solution Focused Therapy',
        'Motivational Interviewing Models',
      ],
      therapyModalityUsed: [
        'Solution Focused Practice',
        'Motivational Interviewing',
      ],
    },
    image: AmandaCruz,
    location: 'Fort Myers',
    name: 'Amanda Cruz',
    position: 'MSW',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AminaRishi,
    location: 'Fort Myers',
    name: 'Amina Rishi',
    position: 'PA-C',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AnnaZiegler,
    location: 'Cape Coral',
    name: 'Anna Ziegler',
    position: 'SLP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AnnikaMatos,
    location: 'Naples',
    name: 'Annika Matos',
    position: 'RMHCI',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AprilSchwartz,
    location: 'Fort Myers',
    name: 'April Schwartz',
    position: 'COTA',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AshleighDePalma,
    location: 'Fort Myers',
    name: 'Ashleigh DePalma',
    position: 'MSW',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AzlundEngler,
    location: 'Fort Myers',
    name: 'Azlund Engler',
    position: 'OTR',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Wheeling Jesuit University'],
      degrees: ['Masters of Science in Nursing'],
      favoriteQuote:
        "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
      hobbies: ['Boating', 'Swimming', 'Outdoors', 'Cooking'],
      hometown: '',
      patientAgesSeen: ['All ages', 'Teen to Geriatric Preferred'],
      specialCertifications: [
        'Family Nurse Practitioner',
        'Board Certified ANCC',
      ],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Port Charlotte',
    name: 'Barbara Tackett',
    position: 'NP',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: BeckyRobertson,
    location: 'Our Team',
    name: 'Becky Robertson',
    position: 'Chief Compliance and Privacy Officer',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: BernardoArias,
    location: 'Port Charlotte',
    name: 'Bernardo Arias',
    position: 'M.D.',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Our Team',
    name: 'Brumy Maldonado',
    position: 'Call Center and Referrals Director',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CandySchings,
    location: 'Our Team',
    name: 'Candy Schings',
    position: 'Director of Revenue Cycle',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CarlaRosier,
    location: 'Fort Myers',
    name: 'Carla Rosier',
    position: 'RMHCI',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CassieSehlmeyer,
    location: 'Our Team',
    name: 'Cassie Sehlmeyer',
    position: 'Executive Assistant',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ChelseaRhoden,
    location: 'Fort Myers',
    name: 'Chelsea Rhoden',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ChristopherGrove,
    location: 'Cape Coral',
    name: 'Christopher Grove',
    position: 'MSW',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ChristaWhelan,
    location: 'Our Team',
    name: 'Christa Whelan',
    position: 'Credentialing & Contracting Manager',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'Leslie University',
        'William James College of Professional Psychology',
      ],
      degrees: [
        'Masters of Counseling Psychology',
        'Doctorate in Clinical Psychology',
      ],
      favoriteQuote: "I'd be brief, but I don’t have time.",
      hobbies: ['Grilling', 'Music'],
      hometown: 'Massachusetts',
      patientAgesSeen: ['Latency (10+ years through Lifespan)'],
      specialCertifications: ['Dialectical Behavipr Therapy'],
      therapyModalityUsed: [
        'Multiple Cognitive Therapies',
        'Behavioral Interventions',
      ],
    },
    image: ChristianRomero,
    location: 'Fort Myers',
    name: 'Christian Romero',
    position: '',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Nova Southwestern'],
      degrees: ['Masters in Speech Pathology'],
      favoriteQuote: '',
      hobbies: ['Kayaking', 'Shopping', 'Traveling', 'Biking'],
      hometown: 'Naples, FL',
      patientAgesSeen: ['Birth to 18'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Crista Macias',
    position: '',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CristinaJohansson,
    location: 'Our Team',
    name: 'Cristina Johansson',
    position: 'Provider Onboarding and Compliance Auditor',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Naples',
    name: 'Danielle Kline',
    position: '',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DawnStarr,
    location: 'Our Team',
    name: 'Dawn Starr',
    position: 'Clinic Manager',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DeliaToledo,
    location: 'Venice',
    name: 'Delia Toledo',
    position: 'M.D.',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DianeRizzitano,
    location: 'Our Team',
    name: 'Diane Rizzitano',
    position: 'Credentialing & Contracting',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DominiqueGasdia,
    location: 'Fort Myers',
    name: 'Dominique Gasdia',
    position: 'RBT',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DorothySmith,
    location: 'Fort Myers',
    name: 'Dorothy Smith',
    position: 'LCSW',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Columbia College of Physicians and Surgeons'],
      degrees: ['MD'],
      favoriteQuote: 'Adversity is a gift to all those on the path.',
      hobbies: [
        'Celebrating Life',
        'Meditating',
        'Gardening',
        'Kayaking',
        'Hiking',
        'Bicycling',
        'Netflix',
        'Yoga',
      ],
      hometown: 'New York',
      patientAgesSeen: ['All ages'],
      specialCertifications: [
        'American Board of Psychiatry and Neurology',
        'Associate Professor of Psychiatry – Albert Einstein College of Medicine – Retired',
        'Director of Osho Institute for the Art of Living and Dying',
      ],
      therapyModalityUsed: [
        'Family Therapy',
        'Pharmaco Therapy',
        'Healing Through Expansion of Consciousness',
      ],
    },
    image: AndrewFerber,
    location: 'Fort Myers',
    name: 'Dr. Andrew Ferber',
    position: 'M.D.',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Fort Myers',
    name: 'Dr. Harvey Shapiro',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MargaretForszpaniak,
    location: 'Naples',
    name: 'Dr. Margaret Forszpaniak',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'University of South Florida',
        'University of North Florida Special Certifications: Family Nurse Practitioner AANP',
        'PMHNP w/ANCC',
      ],
      degrees: [
        'Doctorate of Nursing Practice with Post-Masters Certificate in PMHNP and Global Health',
        'Nursing – UNF. Masters of Science',
        'Family Health Nursing – USF. Bachelors of Science',
        'Nursing – USF',
        'Cum Laude. Associates of Science',
        'Nursing - PHCC',
      ],
      favoriteQuote:
        'Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.',
      hobbies: ['Run Disney Marathons'],
      hometown: 'Poplar Bluff, MO',
      patientAgesSeen: ['2 - 45', '2-30 preferred'],
      specialCertifications: ['Family Nurse Practitioner AANP', 'PMHNP w/ANCC'],
      therapyModalityUsed: ['CBT', 'Mindfullness'],
    },
    image: MarieReeseGorski,
    location: 'Fort Myers',
    name: 'Dr. Marie "Reese" Gorski',
    position: 'ARNP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MatthewTargoff,
    location: 'Fort Myers',
    name: 'Dr. Matthew Targoff',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EdwardPearce,
    location: 'Naples',
    name: 'Edward "Ted" Pearce',
    position: 'PA-C',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ElizabethDosoretz,
    location: 'Our Team',
    name: 'Elizabeth Dosoretz',
    position: 'CEO & Owner',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EllenFerguson,
    location: 'Port Charlotte',
    name: 'Ellen Ferguson',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EmilyAilinger,
    location: 'Fort Myers',
    name: 'Emily Ailinger',
    position: 'MSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EricaKress,
    location: 'Fort Myers',
    name: 'Erica Kress',
    position: 'LCSW',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Gabriel Rivera',
    position: 'NP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: GinaValo,
    location: 'Fort Myers',
    name: 'Gina Valo',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Fort Myers',
    name: 'Guillermo Diaz-Cruz',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida Gulf Coast University'],
      degrees: ['Masters in Clinical Mental Health Counseling'],
      favoriteQuote:
        'Just when the caterpillar thought the world was over, it became a butterfly.',
      hobbies: ['Arts & Crafts', 'Ice Skating', 'Netflix'],
      hometown: '',
      patientAgesSeen: ['All ages'],
      specialCertifications: ['TFCBT'],
      therapyModalityUsed: ['Ecletic'],
    },
    image: HannahThielman,
    location: 'Fort Myers',
    name: 'Hannah Thielman',
    position: '',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: HeatherBrien,
    location: 'Fort Myers',
    name: 'Heather Brien',
    position: '',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Our Team',
    name: 'Isabel Edwards',
    position: 'IT Specialist',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida Atlantic University'],
      degrees: ['Masters in Nursing'],
      favoriteQuote: 'You learn something new everyday.',
      hobbies: ['Reading'],
      hometown: 'Rockledge, FL',
      patientAgesSeen: ['13 - 75'],
      specialCertifications: ['American Academy of Nurse Practitioners'],
      therapyModalityUsed: [],
    },
    image: JacquelineBannister,
    location: 'Fort Myers',
    name: 'Jacqueline Bannister',
    position: 'NP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JairoCastillo,
    location: 'Fort Myers',
    name: 'Jairo Castillo',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JamieMcKenzie,
    location: 'Cape Coral',
    name: 'Jamie McKenzie',
    position: 'LMHC',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JanPaulMojico,
    location: 'Fort Myers',
    name: 'Jan Paul Mojico',
    position: 'LCSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida State University', 'Florida Gulf Coast University'],
      degrees: [
        'Masters in Mental Health Counseling',
        'Masters in Behavior Disorders',
      ],
      favoriteQuote: 'The more I see the less I know for sure.',
      hobbies: ['Music', 'Travel', 'Concerts'],
      hometown: 'Hillsdale, MI',
      patientAgesSeen: ['3 - Geriatric', '3 - Adolescent Preferred'],
      specialCertifications: ['TFCBT (Only in Lee County)'],
      therapyModalityUsed: ['Eclectic'],
    },
    image: JeffreyLapham,
    location: 'Fort Myers',
    name: 'Jeffrey Lapham',
    position: 'LMHC',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: 'Port Charlotte',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JenniferBullistron,
    location: 'Our Team',
    name: 'Jennifer Bullistron',
    position: 'Clinic Manager',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JenniferCordeiro,
    location: 'Fort Myers',
    name: 'Jennifer Cordeiro',
    position: 'SLP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Grand Valley State University'],
      degrees: ['Masters of Nursing', 'Pediatric Nurse Practitioner'],
      favoriteQuote:
        "Promise me you'll always remember: you're braver than you believe, and stronger than you seem, and smarter than you think.",
      hobbies: ['Kayaking', 'Shopping', 'Traveling', 'Biking'],
      hometown: 'Redlands, CA',
      patientAgesSeen: ['5 - 18'],
      specialCertifications: ['Pediatric Primary Mental Health Certification'],
      therapyModalityUsed: ['CBT', 'Eclectic'],
    },
    image: JenniferMoes,
    location: 'Fort Myers',
    name: 'Jennifer Moes',
    position: 'CPNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JenniferThompson,
    location: 'Fort Myers',
    name: 'Jennifer Thompson',
    position: 'MSW',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JillMandeville,
    location: 'Fort Myers',
    name: 'Jill Mandeville',
    position: 'SLPA',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Naples',
    name: 'Jordan Warta',
    position: '',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JoseButron,
    location: 'Fort Myers',
    name: 'Jose Butron',
    position: 'BCBA',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Judith Lenz',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JudithTibera,
    location: 'Port Charlotte',
    name: 'Judith Tibera',
    position: 'ARNP',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KarinSmith,
    location: 'Fort Myers',
    name: 'Karin Smith',
    position: 'COTA',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Naples',
    name: 'Katie Hart',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KimberlyClement,
    location: 'Fort Myers',
    name: 'Kimberly Clement',
    position: 'LMHC',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LilianaAcosta,
    location: 'Cape Coral',
    name: 'Liliana Acosta',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Argosy University', 'Nova Southeastern University'],
      degrees: ['Masters in Education', 'Masters in Mental Health'],
      favoriteQuote: 'Many miles before I sleep.',
      hobbies: ['Reading', 'Cooking', 'Decorating'],
      hometown: 'Miami, FL',
      patientAgesSeen: ['Adults', 'Adolescence', 'Couples', 'Family'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Lily Sanchez',
    position: '',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LindsayGaines,
    location: 'Fort Myers',
    name: 'Lindsay Gaines',
    position: '',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LisaDiamond,
    location: 'Our Team',
    name: 'Lisa Diamond',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LuisNavarrete,
    location: 'Cape Coral',
    name: 'Luis Navarrete',
    position: 'LMHC',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Margaret Barrow',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MarieBoisbel,
    location: 'Fort Myers',
    name: 'Marie Boisbel',
    position: 'MHC',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MelanieOrben,
    location: 'Naples',
    name: 'Melanie Orben',
    position: 'ARNP',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MichaelSchmidt,
    location: 'Our Team',
    name: 'Michael Schmidt',
    position: 'Director of Human Resources & Compliance',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NathanLewis,
    location: 'Our Team',
    name: 'Nathan Lewis',
    position: 'Physician Liaison',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NelsonMonroy,
    location: 'Cape Coral',
    name: 'Nelson Monroy',
    position: 'M.D.',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleBolooki,
    location: 'Our Team',
    name: 'Nicole Bolooki',
    position: 'Director of Payroll & Accounting',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleCochran,
    location: 'Naples',
    name: 'Nicole Cochran',
    position: 'RMHCI',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Nicole Cogswell',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleMillich,
    location: 'Fort Myers',
    name: 'Nicole Millich',
    position: 'ARNP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NoelHelmic,
    location: 'Cape Coral',
    name: 'Noel Helmic',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: PatriciaSullivan,
    location: 'Port Charlotte',
    name: 'Patricia Sullivan',
    position: 'LMHC',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Peta Gay Bezek',
    position: '',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: PhillipCirrone,
    location: 'Our Team',
    name: 'Philip Cirrone',
    position: 'Director of Business Development & Operations',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: RichardGonzalez,
    location: 'Naples',
    name: 'Richard Gonzalez',
    position: 'RMHCI',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Samantha Link',
    position: 'SLP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['University of Toronto', 'University of Western Ontario'],
      degrees: ['Masters of Social Work'],
      favoriteQuote: 'Our thoughts create both our inner and outer world.',
      hobbies: [],
      hometown: '',
      patientAgesSeen: ['10 - 99'],
      specialCertifications: [],
      therapyModalityUsed: ['CBT', 'Eclectic'],
    },
    image: SandraLanders,
    location: 'Port Charlotte',
    name: 'Sandra Landers',
    position: 'LCSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ScarlettOlivaress,
    location: 'Fort Myers',
    name: 'Scarlett Olivaress',
    position: 'RMHCI',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ScottKane,
    location: 'Fort Myers',
    name: 'Scott Kane',
    position: 'PA-C',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: ['FGCU'],
      degrees: ['Bachelors in Psychology'],
      favoriteQuote:
        'Those who judge will never understand, and those who understand will never judge.',
      hobbies: ['Beach', 'Reading', 'Friends', 'Pets'],
      hometown: 'Parkland, FL',
      patientAgesSeen: ['All ages'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ShainaDulong,
    location: 'Fort Myers',
    name: 'Shaina Dulong',
    position: '',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Kaplan University'],
      degrees: ['Masters of Psychology'],
      favoriteQuote: '',
      hobbies: ['Powerlifting', 'Cooking'],
      hometown: 'Kingston, Jamaica',
      patientAgesSeen: ['12+ Outside of Elite', 'Mostly children'],
      specialCertifications: ['Board Certified Behavior Analyst'],
      therapyModalityUsed: [],
    },
    image: ShaneWalters,
    location: 'Fort Myers',
    name: 'Shane Walters',
    position: 'BCBA',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: SharonBloom,
    location: 'Fort Myers',
    name: 'Sharon Bloom',
    position: 'Psy. D',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: SoniaGarcia,
    location: 'Fort Myers',
    name: 'Sonia Garcia',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: SonicaSharma,
    location: 'Naples',
    name: 'Sonica Sharma',
    position: 'MSW',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: StephanieFrost,
    location: 'Naples',
    name: 'Stephanie Frost',
    position: 'OTR',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: TiffanyScott,
    location: 'Fort Myers',
    name: 'Tiffany Scott',
    position: 'LCSW',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: TomEdson,
    location: 'Cape Coral',
    name: 'Tom Edson',
    position: '',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Vickie Campbell',
    position: 'SLP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: WayneMeddock,
    location: 'Fort Myers',
    name: 'Wayne Meddock',
    position: 'LMHC',
  },
]
