const imgPath = '/img/employees/'

const femaleProfile = `${imgPath}female-profile.jpg`
const maleProfile = `${imgPath}male-profile.jpg`

const AdamRedman = `${imgPath}Adam-Redman.jpg`
const AliOrby = `${imgPath}Ali-Orby.jpg`
const AmandaCruz = `${imgPath}Amanda-Cruz.jpg`
const AminaRishi = `${imgPath}Amina-Rishi.jpg`
const AndrewFerber = `${imgPath}Andrew-Ferber.jpg`
const AnnaZiegler = `${imgPath}Anna-Ziegler.jpg`
const AnnikaMatos = `${imgPath}Annika-Matos.jpg`
const AprilSchwartz = `${imgPath}April-Schwartz.jpg`
const AshleighDePalma = `${imgPath}Ashleigh-DePalma.jpg`
const BeckyRobertson = `${imgPath}Becky-Robertson.jpg`
const BernardoArias = `${imgPath}Bernardo-Arias.jpg`
const CandySchings = `${imgPath}Candy-Schings.jpg`
const CarlaRosier = `${imgPath}Carla-Rosier.jpg`
const CassieSehlmeyer = `${imgPath}Cassie-Sehlmeyer.jpg`
const ChelseaRhoden = `${imgPath}Chelsea-Rhoden.jpg`
const ChristopherGrove = `${imgPath}Christopher-Grove.jpg`
const ChristaWhelan = `${imgPath}Christa-Whelan.jpg`
const ChristianRomero = `${imgPath}Christian-Romero.jpg`
const CristinaJohansson = `${imgPath}Cristina-Johansson.jpg`
const DawnStarr = `${imgPath}Dawn-Starr.jpg`
const DeliaToledo = `${imgPath}Delia-Toledo.jpg`
const DianeRizzitano = `${imgPath}Diane-Rizzitano.jpg`
const DominiqueGasdia = `${imgPath}Dominique-Gasdia.jpg`
const DorothySmith = `${imgPath}Dorothy-Smith.jpg`
const EdwardPearce = `${imgPath}Edward-Pearce.jpg`
const ElizabethDosoretz = `${imgPath}Elizabeth-Dosoretz.jpg`
const EllenFerguson = `${imgPath}Ellen-Ferguson.jpg`
const EmilyAilinger = `${imgPath}Emily-Ailinger.jpg`
const EricaKress = `${imgPath}Erica-Kress.jpg`
const GinaValo = `${imgPath}Gina-Valo.jpg`
const HannahThielman = `${imgPath}Hannah-Thielman.jpg`
const HeatherBrien = `${imgPath}Heather-Brien.jpg`
const JacquelineBannister = `${imgPath}Jacqueline-Bannister.jpg`
const JairoCastillo = `${imgPath}Jairo-Castillo.jpg`
const JamieMcKenzie = `${imgPath}Jamie-McKenzie.jpg`
const JanPaulMojico = `${imgPath}Jan-Paul-Mojico.jpg`
const JasonMoon = `${imgPath}Jason-Moon.jpg`
const JeffreyLapham = `${imgPath}Jeffrey-Lapham.jpg`
const JenniferBullistron = `${imgPath}Jennifer-Bullistron.jpg`
const JenniferCordeiro = `${imgPath}Jennifer-Cordeiro.jpg`
const JenniferMoes = `${imgPath}Jennifer-Moes.jpg`
const JenniferThompson = `${imgPath}Jennifer-Thompson.jpg`
const JillMandeville = `${imgPath}Jill-Mandeville.jpg`
const JoseButron = `${imgPath}Jose-Butron.jpg`
const JudithTibera = `${imgPath}Judith-Tibera.jpg`
const KarinSmith = `${imgPath}Karin-Smith.jpg`
const KimberlyClement = `${imgPath}Kimberly-Clement.jpg`
const LilianaAcosta = `${imgPath}Liliana-Acosta.jpg`
const LindsayGaines = `${imgPath}Lindsay-Gaines.jpg`
const LisaDiamond = `${imgPath}Lisa-Diamond.jpg`
const LuisNavarrete = `${imgPath}Luis-Navarrete.jpg`
const MargaretForszpaniak = `${imgPath}Margaret-Forszpaniak.jpg`
const MarieBoisbel = `${imgPath}Marie-Boisbel.jpg`
const MarieReeseGorski = `${imgPath}Marie-Reese-Gorski.jpg`
const MatthewTargoff = `${imgPath}Matthew-Targoff.jpg`
const MelanieOrben = `${imgPath}Melanie-Orben.jpg`
const MichaelSchmidt = `${imgPath}Michael-Schmidt.jpg`
const NathanLewis = `${imgPath}Nathan-Lewis.jpg`
const NelsonMonroy = `${imgPath}Nelson-Monroy.jpg`
const NicoleBolooki = `${imgPath}Nicole-Bolooki.jpg`
const NicoleCochran = `${imgPath}Nicole-Cochran.jpg`
const NicoleMillich = `${imgPath}Nicole-Millich.jpg`
const NoelHelmic = `${imgPath}Noel-Helmic.jpg`
const PatriciaSullivan = `${imgPath}Patricia-Sullivan.jpg`
const PhillipCirrone = `${imgPath}Phillip-Cirrone.jpg`
const RichardGonzalez = `${imgPath}Richard-Gonzalez.jpg`
const SandraLanders = `${imgPath}Sandra-Landers.jpg`
const ScarlettOlivaress = `${imgPath}Scarlett-Olivaress.jpg`
const ScottKane = `${imgPath}Scott-Kane.jpg`
const ShainaDulong = `${imgPath}Shaina-Dulong.jpg`
const ShaneWalters = `${imgPath}Shane-Walters.jpg`
const SharonBloom = `${imgPath}Sharon-Bloom.jpg`
const SoniaGarcia = `${imgPath}Sonia-Garcia.jpg`
const SonicaSharma = `${imgPath}Sonica-Sharma.jpg`
const StephanieFrost = `${imgPath}Stephanie-Frost.jpg`
const TiffanyScott = `${imgPath}Tiffany-Scott.jpg`
const TomEdson = `${imgPath}Tom-Edson.jpg`
const WayneMeddock = `${imgPath}Wayne-Meddock.jpg`

const ourTeam = [
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ElizabethDosoretz,
    location: 'Our Team',
    name: 'Elizabeth Dosoretz',
    position: 'CEO & Owner',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JasonMoon,
    location: 'Our Team',
    name: 'Jason Moon',
    position: 'President',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: PhillipCirrone,
    location: 'Our Team',
    name: 'Philip Cirrone',
    position: 'Director of Business Development & Operations',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleBolooki,
    location: 'Our Team',
    name: 'Nicole Bolooki',
    position: 'Director of Payroll & Accounting',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CandySchings,
    location: 'Our Team',
    name: 'Candy Schings',
    position: 'Director of Revenue Cycle',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DianeRizzitano,
    location: 'Our Team',
    name: 'Diane Rizzitano',
    position: 'Credentialing & Contracting',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CristinaJohansson,
    location: 'Our Team',
    name: 'Cristina Johansson',
    position: 'Provider Onboarding and Compliance Auditor',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MichaelSchmidt,
    location: 'Our Team',
    name: 'Michael Schmidt',
    position: 'Director of Quality Assurance',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CassieSehlmeyer,
    location: 'Our Team',
    name: 'Cassie Sehlmeyer',
    position: 'Executive Assistant',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: BeckyRobertson,
    location: 'Our Team',
    name: 'Becky Robertson',
    position: 'Chief Compliance and Privacy Officer',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Our Team',
    name: 'Brumy Maldonado',
    position: 'Call Center and Referrals Director',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ChristaWhelan,
    location: 'Our Team',
    name: 'Christa Whelan',
    position: 'Credentialing & Contracting Manager',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DawnStarr,
    location: 'Our Team',
    name: 'Dawn Starr',
    position: 'Clinic Manager',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Our Team',
    name: 'Isabel Edwards',
    position: 'IT Specialist',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: 'Port Charlotte',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JenniferBullistron,
    location: 'Our Team',
    name: 'Jennifer Bullistron',
    position: 'Clinic Manager',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LisaDiamond,
    location: 'Our Team',
    name: 'Lisa Diamond',
    position: '',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NathanLewis,
    location: 'Our Team',
    name: 'Nathan Lewis',
    position: 'Physician Liaison',
  },
]

const capeCoral = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NelsonMonroy,
    location: 'Cape Coral',
    name: 'Nelson Monroy',
    position: 'M.D.',
  },
  // a-z
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AliOrby,
    location: 'Cape Coral',
    name: 'Ali Orby',
    position: 'RMHCI',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AnnaZiegler,
    location: 'Cape Coral',
    name: 'Anna Ziegler',
    position: 'SLP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ChristopherGrove,
    location: 'Cape Coral',
    name: 'Christopher Grove',
    position: 'MSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JamieMcKenzie,
    location: 'Cape Coral',
    name: 'Jamie McKenzie',
    position: 'LMHC',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Judith Lenz',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LilianaAcosta,
    location: 'Cape Coral',
    name: 'Liliana Acosta',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Argosy University', 'Nova Southeastern University'],
      degrees: ['Masters in Education', 'Masters in Mental Health'],
      favoriteQuote: 'Many miles before I sleep.',
      hobbies: ['Reading', 'Cooking', 'Decorating'],
      hometown: 'Miami, FL',
      patientAgesSeen: ['Adults', 'Adolescence', 'Couples', 'Family'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Lily Sanchez',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LuisNavarrete,
    location: 'Cape Coral',
    name: 'Luis Navarrete',
    position: 'LMHC',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Margaret Barrow',
    position: 'ARNP',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Nicole Cogswell',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NoelHelmic,
    location: 'Cape Coral',
    name: 'Noel Helmic',
    position: 'ARNP',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: TomEdson,
    location: 'Cape Coral',
    name: 'Tom Edson',
    position: '',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Vickie Campbell',
    position: 'SLP',
  },
]

const fortMeyers = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Columbia College of Physicians and Surgeons'],
      degrees: ['MD'],
      favoriteQuote: 'Adversity is a gift to all those on the path.',
      hobbies: [
        'Celebrating Life',
        'Meditating',
        'Gardening',
        'Kayaking',
        'Hiking',
        'Bicycling',
        'Netflix',
        'Yoga',
      ],
      hometown: 'New York',
      patientAgesSeen: ['All ages'],
      specialCertifications: [
        'American Board of Psychiatry and Neurology',
        'Associate Professor of Psychiatry – Albert Einstein College of Medicine – Retired',
        'Director of Osho Institute for the Art of Living and Dying',
      ],
      therapyModalityUsed: [
        'Family Therapy',
        'Pharmaco Therapy',
        'Healing Through Expansion of Consciousness',
      ],
    },
    image: AndrewFerber,
    location: 'Fort Myers',
    name: 'Dr. Andrew Ferber',
    position: 'M.D.',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'University of South Florida',
        'University of North Florida Special Certifications: Family Nurse Practitioner AANP',
        'PMHNP w/ANCC',
      ],
      degrees: [
        'Doctorate of Nursing Practice with Post-Masters Certificate in PMHNP and Global Health',
        'Nursing – UNF. Masters of Science',
        'Family Health Nursing – USF. Bachelors of Science',
        'Nursing – USF',
        'Cum Laude. Associates of Science',
        'Nursing - PHCC',
      ],
      favoriteQuote:
        'Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.',
      hobbies: ['Run Disney Marathons'],
      hometown: 'Poplar Bluff, MO',
      patientAgesSeen: ['2 - 45', '2-30 preferred'],
      specialCertifications: ['Family Nurse Practitioner AANP', 'PMHNP w/ANCC'],
      therapyModalityUsed: ['CBT', 'Mindfullness'],
    },
    image: MarieReeseGorski,
    location: 'Fort Myers',
    name: 'Dr. Marie "Reese" Gorski',
    position: 'ARNP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MatthewTargoff,
    location: 'Fort Myers',
    name: 'Dr. Matthew Targoff',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: SharonBloom,
    location: 'Fort Myers',
    name: 'Sharon Bloom',
    position: 'Psy. D',
  },
  // a-z
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AdamRedman,
    location: 'Fort Myers',
    name: 'Adam Redman',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Alexandra Bithorn',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'Western New Mexico University',
        'Florida Atlantic University',
      ],
      degrees: ['Masters in Clinical Social Work - Magna Cum Laude'],
      favoriteQuote:
        'Challenges are what make life interesting and overcoming them is what makes life meaningful',
      hobbies: ['Family', 'Exercise', 'Going to the beach'],
      hometown: 'Fort Lauderdale, FL',
      patientAgesSeen: ['12+', 'parents'],
      specialCertifications: [
        'Advanced Training in: Solution Focused Therapy',
        'Motivational Interviewing Models',
      ],
      therapyModalityUsed: [
        'Solution Focused Practice',
        'Motivational Interviewing',
      ],
    },
    image: AmandaCruz,
    location: 'Fort Myers',
    name: 'Amanda Cruz',
    position: 'MSW',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AminaRishi,
    location: 'Fort Myers',
    name: 'Amina Rishi',
    position: 'PA-C',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AprilSchwartz,
    location: 'Fort Myers',
    name: 'April Schwartz',
    position: 'COTA',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AshleighDePalma,
    location: 'Fort Myers',
    name: 'Ashleigh DePalma',
    position: 'MSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CarlaRosier,
    location: 'Fort Myers',
    name: 'Carla Rosier',
    position: 'RMHCI',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ChelseaRhoden,
    location: 'Fort Myers',
    name: 'Chelsea Rhoden',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'Leslie University',
        'William James College of Professional Psychology',
      ],
      degrees: [
        'Masters of Counseling Psychology',
        'Doctorate in Clinical Psychology',
      ],
      favoriteQuote: "I'd be brief, but I don’t have time.",
      hobbies: ['Grilling', 'Music'],
      hometown: 'Massachusetts',
      patientAgesSeen: ['Latency (10+ years through Lifespan)'],
      specialCertifications: ['Dialectical Behavipr Therapy'],
      therapyModalityUsed: [
        'Multiple Cognitive Therapies',
        'Behavioral Interventions',
      ],
    },
    image: ChristianRomero,
    location: 'Fort Myers',
    name: 'Christian Romero',
    position: '',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Nova Southwestern'],
      degrees: ['Masters in Speech Pathology'],
      favoriteQuote: '',
      hobbies: ['Kayaking', 'Shopping', 'Traveling', 'Biking'],
      hometown: 'Naples, FL',
      patientAgesSeen: ['Birth to 18'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Crista Macias',
    position: '',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DominiqueGasdia,
    location: 'Fort Myers',
    name: 'Dominique Gasdia',
    position: 'RBT',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DorothySmith,
    location: 'Fort Myers',
    name: 'Dorothy Smith',
    position: 'LCSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EmilyAilinger,
    location: 'Fort Myers',
    name: 'Emily Ailinger',
    position: 'MSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EricaKress,
    location: 'Fort Myers',
    name: 'Erica Kress',
    position: 'LCSW',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Gabriel Rivera',
    position: 'NP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: GinaValo,
    location: 'Fort Myers',
    name: 'Gina Valo',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Fort Myers',
    name: 'Guillermo Diaz-Cruz',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida Gulf Coast University'],
      degrees: ['Masters in Clinical Mental Health Counseling'],
      favoriteQuote:
        'Just when the caterpillar thought the world was over, it became a butterfly.',
      hobbies: ['Arts & Crafts', 'Ice Skating', 'Netflix'],
      hometown: '',
      patientAgesSeen: ['All ages'],
      specialCertifications: ['TFCBT'],
      therapyModalityUsed: ['Ecletic'],
    },
    image: HannahThielman,
    location: 'Fort Myers',
    name: 'Hannah Thielman',
    position: '',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: HeatherBrien,
    location: 'Fort Myers',
    name: 'Heather Brien',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida Atlantic University'],
      degrees: ['Masters in Nursing'],
      favoriteQuote: 'You learn something new everyday.',
      hobbies: ['Reading'],
      hometown: 'Rockledge, FL',
      patientAgesSeen: ['13 - 75'],
      specialCertifications: ['American Academy of Nurse Practitioners'],
      therapyModalityUsed: [],
    },
    image: JacquelineBannister,
    location: 'Fort Myers',
    name: 'Jacqueline Bannister',
    position: 'NP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JairoCastillo,
    location: 'Fort Myers',
    name: 'Jairo Castillo',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JanPaulMojico,
    location: 'Fort Myers',
    name: 'Jan Paul Mojico',
    position: 'LCSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida State University', 'Florida Gulf Coast University'],
      degrees: [
        'Masters in Mental Health Counseling',
        'Masters in Behavior Disorders',
      ],
      favoriteQuote: 'The more I see the less I know for sure.',
      hobbies: ['Music', 'Travel', 'Concerts'],
      hometown: 'Hillsdale, MI',
      patientAgesSeen: ['3 - Geriatric', '3 - Adolescent Preferred'],
      specialCertifications: ['TFCBT (Only in Lee County)'],
      therapyModalityUsed: ['Eclectic'],
    },
    image: JeffreyLapham,
    location: 'Fort Myers',
    name: 'Jeffrey Lapham',
    position: 'LMHC',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JenniferCordeiro,
    location: 'Fort Myers',
    name: 'Jennifer Cordeiro',
    position: 'SLP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Grand Valley State University'],
      degrees: ['Masters of Nursing', 'Pediatric Nurse Practitioner'],
      favoriteQuote:
        "Promise me you'll always remember: you're braver than you believe, and stronger than you seem, and smarter than you think.",
      hobbies: ['Kayaking', 'Shopping', 'Traveling', 'Biking'],
      hometown: 'Redlands, CA',
      patientAgesSeen: ['5 - 18'],
      specialCertifications: ['Pediatric Primary Mental Health Certification'],
      therapyModalityUsed: ['CBT', 'Eclectic'],
    },
    image: JenniferMoes,
    location: 'Fort Myers',
    name: 'Jennifer Moes',
    position: 'CPNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JenniferThompson,
    location: 'Fort Myers',
    name: 'Jennifer Thompson',
    position: 'MSW',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JillMandeville,
    location: 'Fort Myers',
    name: 'Jill Mandeville',
    position: 'SLPA',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JoseButron,
    location: 'Fort Myers',
    name: 'Jose Butron',
    position: 'BCBA',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KarinSmith,
    location: 'Fort Myers',
    name: 'Karin Smith',
    position: 'COTA',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KimberlyClement,
    location: 'Fort Myers',
    name: 'Kimberly Clement',
    position: 'LMHC',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LindsayGaines,
    location: 'Fort Myers',
    name: 'Lindsay Gaines',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MarieBoisbel,
    location: 'Fort Myers',
    name: 'Marie Boisbel',
    position: 'MHC',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleMillich,
    location: 'Fort Myers',
    name: 'Nicole Millich',
    position: 'ARNP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Peta Gay Bezek',
    position: '',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Samantha Link',
    position: 'SLP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ScarlettOlivaress,
    location: 'Fort Myers',
    name: 'Scarlett Olivaress',
    position: 'RMHCI',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ScottKane,
    location: 'Fort Myers',
    name: 'Scott Kane',
    position: 'PA-C',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: ['FGCU'],
      degrees: ['Bachelors in Psychology'],
      favoriteQuote:
        'Those who judge will never understand, and those who understand will never judge.',
      hobbies: ['Beach', 'Reading', 'Friends', 'Pets'],
      hometown: 'Parkland, FL',
      patientAgesSeen: ['All ages'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ShainaDulong,
    location: 'Fort Myers',
    name: 'Shaina Dulong',
    position: '',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Kaplan University'],
      degrees: ['Masters of Psychology'],
      favoriteQuote: '',
      hobbies: ['Powerlifting', 'Cooking'],
      hometown: 'Kingston, Jamaica',
      patientAgesSeen: ['12+ Outside of Elite', 'Mostly children'],
      specialCertifications: ['Board Certified Behavior Analyst'],
      therapyModalityUsed: [],
    },
    image: ShaneWalters,
    location: 'Fort Myers',
    name: 'Shane Walters',
    position: 'BCBA',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: SoniaGarcia,
    location: 'Fort Myers',
    name: 'Sonia Garcia',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: TiffanyScott,
    location: 'Fort Myers',
    name: 'Tiffany Scott',
    position: 'LCSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: WayneMeddock,
    location: 'Fort Myers',
    name: 'Wayne Meddock',
    position: 'LMHC',
  },
]

const metroGardens = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Fort Myers - Metro Gardens',
    name: 'Dr. Harvey Shapiro',
    position: '',
  },
  // a-z
]

const naples = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MargaretForszpaniak,
    location: 'Naples',
    name: 'Dr. Margaret Forszpaniak',
    position: '',
  },
  // a-z
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AnnikaMatos,
    location: 'Naples',
    name: 'Annika Matos',
    position: 'RMHCI',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Naples',
    name: 'Danielle Kline',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EdwardPearce,
    location: 'Naples',
    name: 'Edward "Ted" Pearce',
    position: 'PA-C',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Naples',
    name: 'Jordan Warta',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Naples',
    name: 'Katie Hart',
    position: 'ARNP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MelanieOrben,
    location: 'Naples',
    name: 'Melanie Orben',
    position: 'ARNP',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleCochran,
    location: 'Naples',
    name: 'Nicole Cochran',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: RichardGonzalez,
    location: 'Naples',
    name: 'Richard Gonzalez',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: SonicaSharma,
    location: 'Naples',
    name: 'Sonica Sharma',
    position: 'MSW',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: StephanieFrost,
    location: 'Naples',
    name: 'Stephanie Frost',
    position: 'OTR',
  },
]

const portCharlotte = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: BernardoArias,
    location: 'Port Charlotte',
    name: 'Bernardo Arias',
    position: 'M.D.',
  },
  // a-z
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Wheeling Jesuit University'],
      degrees: ['Masters of Science in Nursing'],
      favoriteQuote:
        "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
      hobbies: ['Boating', 'Swimming', 'Outdoors', 'Cooking'],
      hometown: '',
      patientAgesSeen: ['All ages', 'Teen to Geriatric Preferred'],
      specialCertifications: [
        'Family Nurse Practitioner',
        'Board Certified ANCC',
      ],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Port Charlotte',
    name: 'Barbara Tackett',
    position: 'NP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EllenFerguson,
    location: 'Port Charlotte',
    name: 'Ellen Ferguson',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EllenFerguson,
    location: 'Port Charlotte',
    name: 'Ellen Ferguson',
    position: 'RMHCI',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JudithTibera,
    location: 'Port Charlotte',
    name: 'Judith Tibera',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: PatriciaSullivan,
    location: 'Port Charlotte',
    name: 'Patricia Sullivan',
    position: 'LMHC',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['University of Toronto', 'University of Western Ontario'],
      degrees: ['Masters of Social Work'],
      favoriteQuote: 'Our thoughts create both our inner and outer world.',
      hobbies: [],
      hometown: '',
      patientAgesSeen: ['10 - 99'],
      specialCertifications: [],
      therapyModalityUsed: ['CBT', 'Eclectic'],
    },
    image: SandraLanders,
    location: 'Port Charlotte',
    name: 'Sandra Landers',
    position: 'LCSW',
  },
]

const venice = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DeliaToledo,
    location: 'Venice',
    name: 'Delia Toledo',
    position: 'M.D.',
  },
  // a-z
]

export const team = []
  .concat(ourTeam)
  .concat(capeCoral)
  .concat(fortMeyers)
  .concat(metroGardens)
  .concat(naples)
  .concat(portCharlotte)
  .concat(venice)
