const imgPath = '/img/employees/'
const badHeightPath = imgPath + 'bad-height/'
const reallyBadHeightPath = imgPath + 'bad-height/really-bad/'

const femaleProfile = `${imgPath}female-profile.jpg`
const maleProfile = `${imgPath}male-profile.jpg`

// Bad Height
const AmandaCruz = `${badHeightPath}Amanda-Cruz.jpg`
const AndrewFerber = `${badHeightPath}Andrew-Ferber.jpg`
const BeckyRobertson = `${badHeightPath}Becky-Robertson.jpg`
const ChristaWhelan = `${badHeightPath}Christa-Whelan.jpg`
const ChristianRomero = `${badHeightPath}Christian-Romero.jpg`
const ChristopherGrove = `${badHeightPath}Christopher-Grove.jpg`
const EmilyAilinger = `${badHeightPath}Emily-Ailinger.jpg`
const GinaValo = `${badHeightPath}Gina-Valo.jpg`
const HannahThielman = `${badHeightPath}Hannah-Thielman.jpg`
const JacquelineBannister = `${badHeightPath}Jacqueline-Bannister.jpg`
const JenniferMoes = `${badHeightPath}Jennifer-Moes.jpg`
const JenniferThompson = `${badHeightPath}Jennifer-Thompson.jpg`
const JessicaBareto = `${badHeightPath}Jessica-Bareto.jpg`
const KristinBryan = `${badHeightPath}Kristin-Bryan.jpg`
const LindsayGaines = `${badHeightPath}Lindsay-Gaines.jpg`
const MarieBoisbel = `${badHeightPath}Marie-Boisbel.jpg`
const MelanieOrben = `${badHeightPath}Melanie-Orben.jpg`
const NathanLewis = `${badHeightPath}Nathan-Lewis.jpg`
const NicoleCochran = `${badHeightPath}Nicole-Cochran.jpg`
const NicoleMillich = `${badHeightPath}Nicole-Millich.jpg`
const ShainaDulong = `${badHeightPath}Shaina-Dulong.jpg`
const SoniaGarcia = `${badHeightPath}Sonia-Garcia.jpg`
const SonicaSharma = `${badHeightPath}Sonica-Sharma.jpg`

// Really Bad Height
const MatthewTargoff = `${reallyBadHeightPath}Matthew-Targoff.jpg`

// Correct Height
const AdamRedman = `${imgPath}Adam-Redman.jpg`
const AliOrby = `${imgPath}Ali-Orby.jpg`
const AngelaMolina = `${imgPath}Angela-Molina.jpg`
const AnnaZiegler = `${imgPath}Anna-Ziegler.jpg`
const AnnikaMatos = `${imgPath}Annika-Matos.jpg`
const AprilTolles = `${imgPath}April-Tolles.jpg`
const AshleighDePalma = `${imgPath}Ashleigh-DePalma.jpg`
const BernardoArias = `${imgPath}Bernardo-Arias.jpg`
const CandySchings = `${imgPath}Candy-Schings.jpg`
const CarlaRosier = `${imgPath}Carla-Rosier.jpg`
const CassieSehlmeyer = `${imgPath}Cassie-Sehlmeyer.jpg`
const ChelseaRhoden = `${imgPath}Chelsea-Rhoden.jpg`
const ChrisJijon = `${imgPath}Chris-Jijon.jpg`
const CristinaJohansson = `${imgPath}Cristina-Johansson.jpg`
const DanielleKline = `${imgPath}Danielle-Kline.jpg`
const DawnStarr = `${imgPath}Dawn-Starr.jpg`
const DeliaToledo = `${imgPath}Delia-Toledo.jpg`
const DianeRizzitano = `${imgPath}Diane-Rizzitano.jpg`
const DominiqueGasdia = `${imgPath}Dominique-Gasdia.jpg`
const DorothySmith = `${imgPath}Dorothy-Smith.jpg`
const EdwardPearce = `${imgPath}Edward-Pearce.jpg`
const ElizabethDosoretz = `${imgPath}Elizabeth-Dosoretz.jpg`
const EllenFerguson = `${imgPath}Ellen-Ferguson.jpg`
const EricaKress = `${imgPath}Erica-Kress.jpg`
const GabbyOgnibene = `${imgPath}Gabby-Ognibene.jpg`
const GabrielNieto = `${imgPath}Gabriel-Nieto.jpg`
const GabrielRivera = `${imgPath}Gabriel-Rivera.jpg`
const GracePasquali = `${imgPath}Grace-Pasquali.jpg`
const GuillermoDiazCruz = `${imgPath}Guillermo-Diaz-Cruz.jpg`
const HarveyShapiro = `${imgPath}Harvey-Shapiro.jpg`
const HeatherBrien = `${imgPath}Heather-Brien.jpg`
const IdelmysGonzalez = `${imgPath}Idelmys-Gonzalez.jpg`
const JairoCastillo = `${imgPath}Jairo-Castillo.jpg`
const JamesKnox = `${imgPath}James-Knox.jpg`
const JamieMcKenzie = `${imgPath}Jamie-McKenzie.jpg`
const JanPaulMojico = `${imgPath}Jan-Paul-Mojico.jpg`
const JasonMoon = `${imgPath}Jason-Moon.jpg`
const JeffreyHutter = `${imgPath}Jeffrey-Hutter.jpg`
const JeffreyLapham = `${imgPath}Jeffrey-Lapham.jpg`
const JenniferBullistron = `${imgPath}Jennifer-Bullistron.jpg`
const JenniferCordeiro = `${imgPath}Jennifer-Cordeiro.jpg`
const JillMandeville = `${imgPath}Jill-Mandeville.jpg`
const JordenWarta = `${imgPath}Jorden-Warta.jpg`
const JoseButron = `${imgPath}Jose-Butron.jpg`
const JudithLenz = `${imgPath}Judith-Lenz.jpg`
const JudithTibera = `${imgPath}Judith-Tibera.jpg`
const KarinSmith = `${imgPath}Karin-Smith.jpg`
const KatieHart = `${imgPath}Katie-Hart.jpg`
const KenCarr = `${imgPath}Ken-Carr.jpg`
const KimberlyClement = `${imgPath}Kimberly-Clement.jpg`
const KristySantana = `${imgPath}Kristy-Santana.jpg`
const LilianaAcosta = `${imgPath}Liliana-Acosta.jpg`
const LisaDiamond = `${imgPath}Lisa-Diamond.jpg`
const LuisNavarrete = `${imgPath}Luis-Navarrete.jpg`
const MarcelaCheca = `${imgPath}Marcela-Checa.jpg`
const MargaretForszpaniak = `${imgPath}Margaret-Forszpaniak.jpg`
const MarieReeseGorski = `${imgPath}Marie-Reese-Gorski.jpg`
const MarkGiordano = `${imgPath}Mark-Giordano.jpg`
const MathewMurel = `${imgPath}Mathew-Murel.jpg`
const MichaelSchmidt = `${imgPath}Michael-Schmidt.jpg`
const NelsonMonroy = `${imgPath}Nelson-Monroy.jpg`
const NicoleBolooki = `${imgPath}Nicole-Bolooki.jpg`
const NicoleCogswell = `${imgPath}Nicole-Cogswell.jpg`
const NoelHelmic = `${imgPath}Noel-Helmic.jpg`
const OmarRieche = `${imgPath}Omar-Rieche.jpg`
const PatriciaSullivan = `${imgPath}Patricia-Sullivan.jpg`
const PetaGayBezek = `${imgPath}Peta-Gay-Bezek.jpg`
const PhillipCirrone = `${imgPath}Phillip-Cirrone.jpg`
const RichardGonzalez = `${imgPath}Richard-Gonzalez.jpg`
const SamanthaLink = `${imgPath}Samantha-Link.jpg`
const SandraLanders = `${imgPath}Sandra-Landers.jpg`
const ScarlettOlivaress = `${imgPath}Scarlett-Olivaress.jpg`
const ScottKane = `${imgPath}Scott-Kane.jpg`
const ShantellPepe = `${imgPath}Shantell-Pepe.jpg`
const SharonBloom = `${imgPath}Sharon-Bloom.jpg`
const StephanieFrost = `${imgPath}Stephanie-Frost.jpg`
const TiffanyScott = `${imgPath}Tiffany-Scott.jpg`
const TomEdson = `${imgPath}Tom-Edson.jpg`
const WayneMeddock = `${imgPath}Wayne-Meddock.jpg`
const YenisTorres = `${imgPath}Yenis-Torres.jpg`

const ourTeam = [
  // primary roles (client ordered)
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ElizabethDosoretz,
    location: 'Our Team',
    name: 'Elizabeth Dosoretz',
    position: 'CEO & Owner',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JasonMoon,
    location: 'Our Team',
    name: 'Jason Moon',
    position: 'President',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: PhillipCirrone,
    location: 'Our Team',
    name: 'Philip Cirrone',
    position: 'Director of Business Development & Operations',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: OmarRieche,
    location: 'Our Team',
    name: 'Dr. Omar Rieche',
    position: 'Medical Director',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KenCarr,
    location: 'Our Team',
    name: 'Ken Carr',
    position: 'CFO',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleBolooki,
    location: 'Our Team',
    name: 'Nicole Bolooki',
    position: 'Director of Payroll & Accounting',
  },
  // a-z
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: BeckyRobertson,
    location: 'Our Team',
    name: 'Becky Robertson',
    position: 'Chief Compliance & Privacy Officer',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Our Team',
    name: 'Brumy Maldonado',
    position: 'Call Center and Referrals Director',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CandySchings,
    location: 'Our Team',
    name: 'Candy Schings',
    position: 'Director of Revenue Cycle',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CassieSehlmeyer,
    location: 'Our Team',
    name: 'Cassie Sehlmeyer',
    position: 'Executive Assistant',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ChristaWhelan,
    location: 'Our Team',
    name: 'Christa Whelan',
    position: 'Credentialing & Contracting Manager',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: CristinaJohansson,
    location: 'Our Team',
    name: 'Cristina Johansson',
    position: 'Provider Onboarding and Compliance Auditor',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DawnStarr,
    location: 'Our Team',
    name: 'Dawn Starr',
    position: 'Clinic Manager',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DianeRizzitano,
    location: 'Our Team',
    name: 'Diane Rizzitano',
    position: 'Credentialing & Contracting',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: GabrielNieto,
    location: 'Our Team',
    name: 'Gabriel Nieto',
    position: '',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Our Team',
    name: 'Isabel Edwards',
    position: 'IT Specialist',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: 'Port Charlotte',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JenniferBullistron,
    location: 'Our Team',
    name: 'Jennifer Bullistron',
    position: 'Clinic Manager',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LisaDiamond,
    location: 'Our Team',
    name: 'Lisa Diamond',
    position: '',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MichaelSchmidt,
    location: 'Our Team',
    name: 'Michael Schmidt',
    position: 'Director of Quality Assurance',
  },
  {
    department: 'Admin',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NathanLewis,
    location: 'Our Team',
    name: 'Nathan Lewis',
    position: 'Physician Liaison',
  },
]

const capeCoral = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NelsonMonroy,
    location: 'Cape Coral',
    name: 'Nelson Monroy',
    position: 'M.D.',
  },
  // a-z
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida International University'],
      degrees: ['Masters in Counseling Psychology'],
      favoriteQuote: 'No one can make you feel inferior without your consent.',
      hobbies: ['Working out', 'Cooking', 'Family'],
      hometown: 'Cape Coral, FL',
      patientAgesSeen: ['All ages', 'Prefer late teens to early 30’s'],
      specialCertifications: ['Licensed Mental Health Counselor'],
      therapyModalityUsed: ['CBT', 'Play therapy', 'Person centered'],
    },
    image: AliOrby,
    location: 'Cape Coral',
    name: 'Ali Orby',
    position: 'RMHCI',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AnnaZiegler,
    location: 'Cape Coral',
    name: 'Anna Ziegler',
    position: 'SLP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['University of Pittsburgh'],
      degrees: ['Masters in Social Work'],
      favoriteQuote:
        'And now that you don’t have to be perfect, you can be good.',
      hobbies: [
        'Mixed Martial Arts',
        'Biking',
        'Disc Golf',
        'Exploring Cape Coral',
      ],
      hometown: 'Huntington, PA',
      patientAgesSeen: ['All ages'],
      specialCertifications: ['Certified Nurturing Parenting Instructor'],
      therapyModalityUsed: [
        'CBT',
        'DBT',
        'Motivation',
        'Parent Management Training',
      ],
    },
    image: ChristopherGrove,
    location: 'Cape Coral',
    name: 'Christopher Grove',
    position: 'RSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JamesKnox,
    location: 'Cape Coral',
    name: 'James Knox',
    position: 'NP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JamieMcKenzie,
    location: 'Cape Coral',
    name: 'Jamie McKenzie',
    position: 'LMHC',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JudithLenz,
    location: 'Cape Coral',
    name: 'Judith Lenz',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LilianaAcosta,
    location: 'Cape Coral',
    name: 'Liliana Acosta',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Argosy University', 'Nova Southeastern University'],
      degrees: ['Masters in Education', 'Masters in Mental Health'],
      favoriteQuote: 'Many miles before I sleep.',
      hobbies: ['Reading', 'Cooking', 'Decorating'],
      hometown: 'Miami, FL',
      patientAgesSeen: ['Adults', 'Adolescence', 'Couples', 'Family'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Liliana Acosta',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LuisNavarrete,
    location: 'Cape Coral',
    name: 'Luis Navarrete',
    position: 'LMHC',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Margaret Barrow',
    position: 'ARNP',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MathewMurel,
    location: 'Cape Coral',
    name: 'Mathew Murel',
    position: '',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleCogswell,
    location: 'Cape Coral',
    name: 'Nicole Cogswell',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NoelHelmic,
    location: 'Cape Coral',
    name: 'Noel Helmic',
    position: 'ARNP',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: TomEdson,
    location: 'Cape Coral',
    name: 'Tom Edson',
    position: '',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Cape Coral',
    name: 'Vickie Campbell',
    position: 'SLP',
  },
]

const fortMeyers = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Columbia College of Physicians and Surgeons'],
      degrees: ['MD'],
      favoriteQuote: 'Adversity is a gift to all those on the path.',
      hobbies: [
        'Celebrating Life',
        'Meditating',
        'Gardening',
        'Kayaking',
        'Hiking',
        'Bicycling',
        'Netflix',
        'Yoga',
      ],
      hometown: 'New York',
      patientAgesSeen: ['All ages'],
      specialCertifications: [
        'American Board of Psychiatry and Neurology',
        'Associate Professor of Psychiatry – Albert Einstein College of Medicine – Retired',
        'Director of Osho Institute for the Art of Living and Dying',
      ],
      therapyModalityUsed: [
        'Family Therapy',
        'Pharmaco Therapy',
        'Healing Through Expansion of Consciousness',
      ],
    },
    image: AndrewFerber,
    location: 'Fort Myers',
    name: 'Dr. Andrew Ferber',
    position: 'M.D.',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'University of South Florida',
        'University of North Florida Special Certifications: Family Nurse Practitioner AANP',
        'PMHNP w/ANCC',
      ],
      degrees: [
        'Doctorate of Nursing Practice with Post-Masters Certificate in PMHNP and Global Health',
        'Nursing – UNF. Masters of Science',
        'Family Health Nursing – USF. Bachelors of Science',
        'Nursing – USF',
        'Cum Laude. Associates of Science',
        'Nursing - PHCC',
      ],
      favoriteQuote:
        'Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.',
      hobbies: ['Run Disney Marathons'],
      hometown: 'Poplar Bluff, MO',
      patientAgesSeen: ['2 - 45', '2-30 preferred'],
      specialCertifications: ['Family Nurse Practitioner AANP', 'PMHNP w/ANCC'],
      therapyModalityUsed: ['CBT', 'Mindfullness'],
    },
    image: MarieReeseGorski,
    location: 'Fort Myers',
    name: 'Dr. Marie "Reese" Gorski',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MarkGiordano,
    location: 'Fort Myers',
    name: 'Dr. Mark Giordano',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MatthewTargoff,
    location: 'Fort Myers',
    name: 'Dr. Matthew Targoff',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'Colgate University',
        'Ferkauf Graduate School of Psychology at Yeshiva University',
        'NYU Institute for Psychoanalytic Education',
      ],
      degrees: ['Doctorate in Clinical Psychology'],
      favoriteQuote: '',
      hobbies: ['Baking', 'Books', 'Bootcamp'],
      hometown: 'Scarsdale, NY',
      patientAgesSeen: ['All ages', 'Mainly 4-64'],
      specialCertifications: [
        'Postdoc training in Psychodynamic Psychotherapy of Children and Adolescents',
      ],
      therapyModalityUsed: ['CBT', 'Psychodynamic Psychotherapy'],
    },
    image: SharonBloom,
    location: 'Fort Myers',
    name: 'Dr. Sharon Bloom',
    position: 'PsyD',
  },
  // a-z
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [
        'Anxiety',
        'Depression',
        'Trauma',
        'ADHD',
        'Autism Spectrum',
        'Mood disorders',
        'ODD',
      ],
      colleges: ['Florida State University', 'Florida Gulf Coast University'],
      degrees: ['BS', 'MA', 'CACREP', 'CMHC', 'LMC'],
      favoriteQuote:
        'We must be willing to encounter darkness and despair when they come up and face them, over and over again if need be, without running away or numbing ourselves in the thousands of ways we conjure up to avoid the unavoidable.',
      hobbies: ['Video Games/Board Games'],
      hometown: 'Fort Myers, FL',
      patientAgesSeen: [
        'Six and up (in office)',
        'Adolescent & Adult (telemedicine)',
      ],
      specialCertifications: [],
      therapyModalityUsed: ['ACT', 'CPT', 'Solution Focused Behavior Plans'],
    },
    image: AdamRedman,
    location: 'Fort Myers',
    name: 'Adam Redman',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Alexandra Bithorn',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'Western New Mexico University',
        'Florida Atlantic University',
      ],
      degrees: ['Masters in Clinical Social Work - Magna Cum Laude'],
      favoriteQuote:
        'Challenges are what make life interesting and overcoming them is what makes life meaningful',
      hobbies: ['Family', 'Exercise', 'Going to the beach'],
      hometown: 'Fort Lauderdale, FL',
      patientAgesSeen: ['12+', 'parents'],
      specialCertifications: [
        'Advanced Training in: Solution Focused Therapy',
        'Motivational Interviewing Models',
      ],
      therapyModalityUsed: [
        'Solution Focused Practice',
        'Motivational Interviewing',
      ],
    },
    image: AmandaCruz,
    location: 'Fort Myers',
    name: 'Amanda Cruz',
    position: 'MSW',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'Florida Southwestern State College',
        'FGCU',
        'Keiser University',
      ],
      degrees: [
        'Associates of Science',
        "Bachelor's Degree in Health & Science",
      ],
      favoriteQuote:
        'The one who falls and gets up is so much stronger than the one who never fell',
      hobbies: ['Working out', 'Outdoor activities with my boys'],
      hometown: 'Pawtucket, RI',
      patientAgesSeen: ['Pediatrics (typically ages 2-17)'],
      specialCertifications: [
        'Handwriting Without Tears Trained',
        'Interactive Metranome Certified',
      ],
      therapyModalityUsed: [],
    },
    image: AprilTolles,
    location: 'Fort Myers',
    name: 'April Tolles',
    position: 'COTA',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['University of Southern California'],
      degrees: ['Masters in Social Work'],
      favoriteQuote:
        'To live every day as if it had been stolen from death, that is how I would like to live. To separate oneself from the burden, the angst, the anguish that we all encounter every day. To say I am alive, I am wonderful, I am. I am. That is something to aspire to.',
      hobbies: ['Soccer', 'Raising Butterflies', 'Wildlife Conservation'],
      hometown: 'Royal Oak, MI',
      patientAgesSeen: ['All ages'],
      specialCertifications: ['Handle with Care', 'First Aid', 'CPR'],
      therapyModalityUsed: [
        'CBT',
        'DBT',
        'Positive Psychotherapy',
        'Ecotherapy',
      ],
    },
    image: AshleighDePalma,
    location: 'Fort Myers',
    name: 'Ashleigh DePalma',
    position: 'MSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Hodges University'],
      degrees: ['Masters of Science in Clinical Mental Health Counseling'],
      favoriteQuote:
        'Life is not about finding yourself, it is about creating yourself.',
      hobbies: [
        'Bowling',
        'Beach',
        'Family',
        'Thriller Movies',
        'Gardening',
        'Cooking',
      ],
      hometown: 'Miami, FL',
      patientAgesSeen: ['6 – geriatric', 'prefers teens & adolescents'],
      specialCertifications: [],
      therapyModalityUsed: ['CBT', 'Secondary Solution Focused'],
    },
    image: CarlaRosier,
    location: 'Fort Myers',
    name: 'Carla Rosier',
    position: 'RMHCI',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: ['University of South Florida'],
      degrees: ['Bachelors in Criminology & Psychology'],
      favoriteQuote: '',
      hobbies: ['Tennis', 'Golf', 'Kayaking', 'Beach', 'Running'],
      hometown: 'Clermont, FL',
      patientAgesSeen: ['All ages'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ChelseaRhoden,
    location: 'Fort Myers',
    name: 'Chelsea Rhoden',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ChrisJijon,
    location: 'Fort Myers',
    name: 'Chris Jijon',
    position: 'PA-C',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'Leslie University',
        'William James College of Professional Psychology',
      ],
      degrees: [
        'Masters of Counseling Psychology',
        'Doctorate in Clinical Psychology',
      ],
      favoriteQuote: "I'd be brief, but I don’t have time.",
      hobbies: ['Grilling', 'Music'],
      hometown: 'Massachusetts',
      patientAgesSeen: ['Latency (10+ years through Lifespan)'],
      specialCertifications: ['Dialectical Behavipr Therapy'],
      therapyModalityUsed: [
        'Multiple Cognitive Therapies',
        'Behavioral Interventions',
      ],
    },
    image: ChristianRomero,
    location: 'Fort Myers',
    name: 'Christian Romero',
    position: '',
  },
  {
    department: 'Speech Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Nova Southwestern'],
      degrees: ['Masters in Speech Pathology'],
      favoriteQuote: '',
      hobbies: ['Kayaking', 'Shopping', 'Traveling', 'Biking'],
      hometown: 'Naples, FL',
      patientAgesSeen: ['Birth to 18'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Fort Myers',
    name: 'Crista Macias',
    position: 'SLP-A',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Kaplan University', 'Kean University'],
      degrees: ['Masters in Applied Behavioral Analysis'],
      favoriteQuote:
        'Everybody is a genius, but if you judge a fish by its ability to climb a tree, it will live its entire life believing it’s stupid.',
      hobbies: [
        'Reading',
        'Cooking',
        'Gardening',
        'Learning about Holistic Healing',
        'Walking/Hiking',
        'Old Movies',
      ],
      hometown: 'Manalapan, NJ',
      patientAgesSeen: ['2-75'],
      specialCertifications: [
        'NJ appointed trainer in Medication Administration',
        'Preventing Abuse and Neglect',
        'Overview of Developmental Disabilities',
      ],
      therapyModalityUsed: [
        'Errorless Learning',
        'Verbal Behavior',
        'Positive Behavior Supports',
      ],
    },
    image: DominiqueGasdia,
    location: 'Fort Myers',
    name: 'Dominique Gasdia',
    position: 'RBT',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['University of Kentucky', 'University of South Florida'],
      degrees: ['BS', 'Masters'],
      favoriteQuote: 'Nothing good comes easy.',
      hobbies: [],
      hometown: 'Harlan County, KY',
      patientAgesSeen: ['All ages'],
      specialCertifications: [
        'E-Therapy',
        'Online Therapy utilizing face-to-face technology',
      ],
      therapyModalityUsed: [],
    },
    image: DorothySmith,
    location: 'Fort Myers',
    name: 'Dorothy Smith',
    position: 'LCSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EmilyAilinger,
    location: 'Fort Myers',
    name: 'Emily Ailinger',
    position: 'MSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: ['ADHD', 'ODD', 'Anxiety'],
      colleges: [
        'University of Pittsburgh',
        'ADD Coach',
        'Academy-Advanced Training in ADHD Coaching',
      ],
      degrees: ['Masters in Clinical Social Work'],
      favoriteQuote: '',
      hobbies: ['Workout', 'Family', 'Travel'],
      hometown: 'Ambridge, PA',
      patientAgesSeen: ['6+', 'Parents'],
      specialCertifications: [],
      therapyModalityUsed: ['CBT'],
    },
    image: EricaKress,
    location: 'Fort Myers',
    name: 'Erica Kress',
    position: 'LCSW',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: GabbyOgnibene,
    location: 'Fort Myers',
    name: 'Gabby Ognibene',
    position: 'RBT',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: GabrielRivera,
    location: 'Fort Myers',
    name: 'Gabriel Rivera',
    position: 'NP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [
        'Middlesex County College',
        'University of South Florida',
        'South University',
      ],
      degrees: ['Associates', 'Bachelors', 'Masters'],
      favoriteQuote:
        'Things may come to those who wait, but only the things left by those who hustle.',
      hobbies: ['Reading', 'Hiking', 'Cross Stitch', 'Needlepoint', 'Music'],
      hometown: 'Carteret, NJ',
      patientAgesSeen: ['Adults'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: GinaValo,
    location: 'Fort Myers',
    name: 'Gina Valo',
    position: 'ARNP',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: GracePasquali,
    location: 'Fort Myers',
    name: 'Grace Pasquali',
    position: 'COTA',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: GuillermoDiazCruz,
    location: 'Fort Myers',
    name: 'Guillermo Diaz-Cruz',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida Gulf Coast University'],
      degrees: ['Masters in Clinical Mental Health Counseling'],
      favoriteQuote:
        'Just when the caterpillar thought the world was over, it became a butterfly.',
      hobbies: ['Arts & Crafts', 'Ice Skating', 'Netflix'],
      hometown: '',
      patientAgesSeen: ['All ages'],
      specialCertifications: ['TFCBT'],
      therapyModalityUsed: ['Ecletic'],
    },
    image: HannahThielman,
    location: 'Fort Myers',
    name: 'Hannah Thielman',
    position: '',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: HeatherBrien,
    location: 'Fort Myers',
    name: 'Heather Brien',
    position: '',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: IdelmysGonzalez,
    location: 'Fort Myers',
    name: 'Idelmys Gonzalez',
    position: 'RBT',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida Atlantic University'],
      degrees: ['Masters in Nursing'],
      favoriteQuote: 'You learn something new everyday.',
      hobbies: ['Reading'],
      hometown: 'Rockledge, FL',
      patientAgesSeen: ['13 - 75'],
      specialCertifications: ['American Academy of Nurse Practitioners'],
      therapyModalityUsed: [],
    },
    image: JacquelineBannister,
    location: 'Fort Myers',
    name: 'Jacqueline Bannister',
    position: 'NP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JairoCastillo,
    location: 'Fort Myers',
    name: 'Jairo Castillo',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JanPaulMojico,
    location: 'Fort Myers',
    name: 'Jan Paul Mojico',
    position: 'LCSW',
  },
  {
    department: 'Psychology',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JeffreyHutter,
    location: 'Fort Myers',
    name: 'Jeffrey Hutter',
    position: 'RCSWI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida State University', 'Florida Gulf Coast University'],
      degrees: [
        'Masters in Mental Health Counseling',
        'Masters in Behavior Disorders',
      ],
      favoriteQuote: 'The more I see the less I know for sure.',
      hobbies: ['Music', 'Travel', 'Concerts'],
      hometown: 'Hillsdale, MI',
      patientAgesSeen: ['3 - Geriatric', '3 - Adolescent Preferred'],
      specialCertifications: ['TFCBT (Only in Lee County)'],
      therapyModalityUsed: ['Eclectic'],
    },
    image: JeffreyLapham,
    location: 'Fort Myers',
    name: 'Jeffrey Lapham',
    position: 'LMHC',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JenniferCordeiro,
    location: 'Fort Myers',
    name: 'Jennifer Cordeiro',
    position: 'SLP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Grand Valley State University'],
      degrees: ['Masters of Nursing', 'Pediatric Nurse Practitioner'],
      favoriteQuote:
        "Promise me you'll always remember: you're braver than you believe, and stronger than you seem, and smarter than you think.",
      hobbies: ['Kayaking', 'Shopping', 'Traveling', 'Biking'],
      hometown: 'Redlands, CA',
      patientAgesSeen: ['5 - 18'],
      specialCertifications: ['Pediatric Primary Mental Health Certification'],
      therapyModalityUsed: ['CBT', 'Eclectic'],
    },
    image: JenniferMoes,
    location: 'Fort Myers',
    name: 'Jennifer Moes',
    position: 'CPNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JenniferThompson,
    location: 'Fort Myers',
    name: 'Jennifer Thompson',
    position: 'MSW',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JessicaBareto,
    location: 'Fort Myers',
    name: 'Jessica Bareto',
    position: '',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JillMandeville,
    location: 'Fort Myers',
    name: 'Jill Mandeville',
    position: 'SLPA',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JordenWarta,
    location: 'Fort Myers',
    name: 'Jorden Warta',
    position: '',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JoseButron,
    location: 'Fort Myers',
    name: 'Jose Butron',
    position: 'BCBA',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KarinSmith,
    location: 'Fort Myers',
    name: 'Karin Smith',
    position: 'COTA',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KimberlyClement,
    location: 'Fort Myers',
    name: 'Kimberly Clement',
    position: 'LMHC',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KristinBryan,
    location: 'Fort Myers',
    name: 'Kristin Bryan',
    position: 'ARNP',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KristySantana,
    location: 'Fort Myers',
    name: 'Kristy Santana',
    position: '',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: LindsayGaines,
    location: 'Fort Myers',
    name: 'Lindsay Gaines',
    position: '',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MarcelaCheca,
    location: 'Fort Myers',
    name: 'Marcela Checa',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MarieBoisbel,
    location: 'Fort Myers',
    name: 'Marie Boisbel',
    position: 'MHC',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleMillich,
    location: 'Fort Myers',
    name: 'Nicole Millich',
    position: 'ARNP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: PetaGayBezek,
    location: 'Fort Myers',
    name: 'Peta Gay Bezek',
    position: 'PMHNP',
  },
  {
    department: 'Speech',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: SamanthaLink,
    location: 'Fort Myers',
    name: 'Samantha Link',
    position: 'SLP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ScarlettOlivaress,
    location: 'Fort Myers',
    name: 'Scarlett Olivaress',
    position: 'RMHCI',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ScottKane,
    location: 'Fort Myers',
    name: 'Scott Kane',
    position: 'PA-C',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: ['FGCU'],
      degrees: ['Bachelors in Psychology'],
      favoriteQuote:
        'Those who judge will never understand, and those who understand will never judge.',
      hobbies: ['Beach', 'Reading', 'Friends', 'Pets'],
      hometown: 'Parkland, FL',
      patientAgesSeen: ['All ages'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ShainaDulong,
    location: 'Fort Myers',
    name: 'Shaina Dulong',
    position: '',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: ShantellPepe,
    location: 'Fort Myers',
    name: 'Shantell Pepe',
    position: 'LMHC',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: SoniaGarcia,
    location: 'Fort Myers',
    name: 'Sonia Garcia',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: TiffanyScott,
    location: 'Fort Myers',
    name: 'Tiffany Scott',
    position: 'LCSW',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: WayneMeddock,
    location: 'Fort Myers',
    name: 'Wayne Meddock',
    position: 'LMHC',
  },
  {
    department: 'Behavior Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['University of La Habana'],
      degrees: ['Bachelors'],
      favoriteQuote: 'Jose marti. Solo va al alma lo que nace del alma',
      hobbies: ['TV', 'Cooking', 'Cuban food', 'Shopping'],
      hometown: 'La Habana, Regla',
      patientAgesSeen: ['3-12'],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: YenisTorres,
    location: 'Fort Myers',
    name: 'Yenis Torres',
    position: 'ABA',
  },
]

const metroGardens = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: HarveyShapiro,
    location: 'Fort Myers - Metro Gardens',
    name: 'Dr. Harvey Shapiro',
    position: '',
  },
  // a-z
]

const naples = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: KatieHart,
    location: 'Naples',
    name: 'Dr. Katie Hart',
    position: 'ARNP',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Rollins College'],
      degrees: ['D.O.', 'Masters in Chemistry & Molecular Biology'],
      favoriteQuote: '',
      hobbies: ['Dogs', 'Beach', 'Cooking/Baking', 'Yoga'],
      hometown: 'Naples, FL',
      patientAgesSeen: ['3 - Geriatric', 'prefers children'],
      specialCertifications: ['Sleep Medicine'],
      therapyModalityUsed: ['CBT', 'Psychodynamic'],
    },
    image: MargaretForszpaniak,
    location: 'Naples',
    name: 'Dr. Margaret Forszpaniak',
    position: '',
  },
  // a-z
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: AngelaMolina,
    location: 'Naples',
    name: 'Angela Molina',
    position: '',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Florida Gulf Coast University'],
      degrees: ['Masters in Clinical Social Work'],
      favoriteQuote: 'When you know better, you do better.',
      hobbies: ['Animal Rescue', 'Volunteering'],
      hometown: 'Tappan, NY',
      patientAgesSeen: ['All ages', 'Prefers trauma patients'],
      specialCertifications: [],
      therapyModalityUsed: ['Eclectic'],
    },
    image: AnnikaMatos,
    location: 'Naples',
    name: 'Annika Matos',
    position: 'RMHCI',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DanielleKline,
    location: 'Naples',
    name: 'Danielle Kline',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: EdwardPearce,
    location: 'Naples',
    name: 'Edward "Ted" Pearce',
    position: 'PA-C',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: maleProfile,
    location: 'Naples',
    name: 'Jordan Warta',
    position: '',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: MelanieOrben,
    location: 'Naples',
    name: 'Melanie Orben',
    position: 'ARNP',
  },
  {
    department: 'Care Coordinators',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: NicoleCochran,
    location: 'Naples',
    name: 'Nicole Cochran',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: RichardGonzalez,
    location: 'Naples',
    name: 'Richard Gonzalez',
    position: 'RMHCI',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: SonicaSharma,
    location: 'Naples',
    name: 'Sonica Sharma',
    position: 'MSW',
  },
  {
    department: 'Occupational Therapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: StephanieFrost,
    location: 'Naples',
    name: 'Stephanie Frost',
    position: 'OTR',
  },
]

const parkRoyal = []

const portCharlotte = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Boston University'],
      degrees: ['MD'],
      favoriteQuote: '',
      hobbies: ['Exercise'],
      hometown: 'Port Charlotte, FL',
      patientAgesSeen: ['All ages'],
      specialCertifications: [],
      therapyModalityUsed: ['Eclectic'],
    },
    image: BernardoArias,
    location: 'Port Charlotte',
    name: 'Dr. Bernardo Arias',
    position: 'M.D.',
  },
  // a-z
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Wheeling Jesuit University'],
      degrees: ['Masters of Science in Nursing'],
      favoriteQuote:
        "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
      hobbies: ['Boating', 'Swimming', 'Outdoors', 'Cooking'],
      hometown: '',
      patientAgesSeen: ['All ages', 'Teen to Geriatric Preferred'],
      specialCertifications: [
        'Family Nurse Practitioner',
        'Board Certified ANCC',
      ],
      therapyModalityUsed: [],
    },
    image: femaleProfile,
    location: 'Port Charlotte',
    name: 'Barbara Tackett',
    position: 'NP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['Indiana University', 'Purdue University'],
      degrees: ['Masters in Counseling Psychology'],
      favoriteQuote:
        'If you always do what you always did, you will always get what you always got.',
      hobbies: ['Beach'],
      hometown: 'Indianapolis, IN',
      patientAgesSeen: ['All ages', 'Prefer teens and young adults'],
      specialCertifications: [],
      therapyModalityUsed: ['CBT', 'Eclectic'],
    },
    image: EllenFerguson,
    location: 'Port Charlotte',
    name: 'Ellen Ferguson',
    position: 'RMHCI',
  },
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: JudithTibera,
    location: 'Port Charlotte',
    name: 'Judith Tibera',
    position: 'ARNP',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: PatriciaSullivan,
    location: 'Port Charlotte',
    name: 'Patricia Sullivan',
    position: 'LMHC',
  },
  {
    department: 'Psychotherapy',
    details: {
      clientPopulationsSeen: [],
      colleges: ['University of Toronto', 'University of Western Ontario'],
      degrees: ['Masters of Social Work'],
      favoriteQuote: 'Our thoughts create both our inner and outer world.',
      hobbies: [],
      hometown: '',
      patientAgesSeen: ['10 - 99'],
      specialCertifications: [],
      therapyModalityUsed: ['CBT', 'Eclectic'],
    },
    image: SandraLanders,
    location: 'Port Charlotte',
    name: 'Sandra Landers',
    position: 'LCSW',
  },
]

const venice = [
  // doctors
  {
    department: 'Psychiatry',
    details: {
      clientPopulationsSeen: [],
      colleges: [],
      degrees: [],
      favoriteQuote: '',
      hobbies: [],
      hometown: '',
      patientAgesSeen: [],
      specialCertifications: [],
      therapyModalityUsed: [],
    },
    image: DeliaToledo,
    location: 'Venice',
    name: 'Delia Toledo',
    position: 'M.D.',
  },
]

export const team = []
  .concat(ourTeam)
  .concat(capeCoral)
  .concat(fortMeyers)
  .concat(metroGardens)
  .concat(naples)
  .concat(parkRoyal)
  .concat(portCharlotte)
  .concat(venice)
